version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: Sunil
      POSTGRES_DB: sdc
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./api:/api
    ports:
      - '5432:5432'
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'server'
    environment:
      DB_HOST: host.docker.internal
      DB_USER: Sunil
      DB_PASS: password
    volumes:
      - ./api:/api
    ports:
      - '3004:3004'
